### ISSUE TITLE
Fix / Invitation - Invitable user list should only display users from the company (so being in a team)  that are not already in team or not captain

### ISSUE THREAD

**Issue by LaurentMag** [XPEHO/YAKI#1372]
## Context
In the current application version the user invitation list contain every user from the database.
We should only display users affiliated to the company related to the customer teams.

## Todo

- [x] Edit end point "/users" in __UserController.java__ : 
    -  to carry ?customer={customerId}&excludeCaptains query params that allow to get the list of invitable user to become a captain (users in customer not already captain for this one)
    - to carry ?customer={customerId}&excludeTeam={teamId} query params that allow to get the list of invitable user to join the team (users in customer not already in the team with id = teamId)

- [x] Make changes in __UserService.java__ and __UserServiceImpl.java__ for method _findAllUsers_ to make a call depending new params
- [x] Make changes in __UserJpaRepository.java__ to create new methods _findAllEnabledUsersByCustomer_, _findAllEnabledUsersByCustomerExcludingCaptains_ and _findAllEnabledUsersByCustomerExcludingTeam_ to use new params in query

## BLOCKING POINT
Problem of knowledge for unit tests.
