### ISSUE TITLE
Add stats visualisation in the statistics page

### ISSUE THREAD

**Issue by LaurentMag** [XPEHO/YAKI#1435]
## Context
![Image](https://github.com/XPEHO/YAKI/assets/95299697/c1592c4a-1606-45b4-b2c5-c8e399b13bca)

the statistic page should display the selected stat, and then let the user download the said statistics if so desired.

It will allow administrator to have a initial and quick visualisation of the data.

## Todo
- [x] Create a method that read csv to get its datas in a a two-dimensional array of string
- [x] Create a vue component that take a two-dimensional array of string in parameter and display a table with a correct design
- [x] Call the method and give the result to the component in the statistics view
- [ ] Add pagination to the table
