### ISSUE TITLE
Chore / Rules - Define ticket name and content rules

### ISSUE THREAD

**Issue by NyraSama** [XPEHO/YAKI#1461]
# Context
Currently the tickets have a naming process that is not constant that create a backlog less readable.
We also have tickets with differents content format and some with not enough details.

# PR Link
[https://github.com/XPEHO/YAKI/pull/1485](Templates)

# ToDo
- [x] Define together a rule for naming system
- [x] Define according the DOR/DOD a content format that need to be filled to have enough details 
- [x] Create templates for 3 case:
    - [x] Feature
    - [x] Fix
    - [x] UI
