### ISSUE TITLE
Feat / Statistic - Create preview table design in figma

### ISSUE THREAD

**Issue by NyraSama** [XPEHO/YAKI#1483]
# 🗒️NOTES

# 🏁MILESTONES

- [ ]  **DOR**
- [ ]  **DOD**
- [ ] End user validation
- [ ] Customer validation 

# 📜CONTEXT (User Story)

**As a** dev

**I want to** allow the yaki's ui components available to the entire world

**In order to** do this, i need to create a design for a table used to preview a csv content

# 🪜STEPS TO FOLLOW

- [ ] Step 1: Design the table
- [ ] Step 2: Ask the end user feedback
- [ ] Step 3: Make changes if needed
- [ ] Step 4: Make a presentation to the customer

# ✅ACCEPTANCE CRITERIA

- ✅ The table follows the same idea as Basti UI's yaki design

# 📛BLOCKERS

# 🔍AFFECTED COMPONENT(S) (Scope)

# ⛓️LINK TO OTHER ISSUES

# 🪟SCREEN SHOTS & MOCKUPS
